routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

// admin access
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

// Profile
Route::get('profile', 'ProfileController@index')->name('profile.index');
Route::get('profile/logout', 'ProfileController@logout')->name('profile.logout');


// manage permission
Route::resource('permissions', 'PermissionsController')->except(['show']);


// manage role
Route::get('roles/toggle-sync-permission/{role_id}/{permission_id}', 'RolesController@toggleSyncPermission')->name('roles.toggle.sync.permission');
Route::resource('roles', 'RolesController')->except(['show']);


// manage user
Route::prefix('users/{id}/minitutor')->as('users.minitutor.')->group(function(){
    Route::get('/create', 'UsersController@createMinitutor')->name('create');
    Route::post('/', 'UsersController@storeMinitutor')->name('store');
});
Route::get('users/{id}/followings', 'UsersController@showFollowings')->name('users.show.followings');
Route::get('users/{id}/favorites', 'UsersController@showFavorites')->name('users.show.favorites');
Route::resource('users', 'UsersController');


// manage minitutor
Route::prefix('minitutors')->as('minitutors.')->group(function(){
    Route::get('{id}/active-toggle', 'MinitutorsController@activeToggle')->name('active.toggle');
    Route::get('requests', 'MinitutorsController@requests')->name('requests');
    Route::get('request/{id}', 'MinitutorsController@showRequest')->name('request.show');
    Route::put('request/{id}/accept', 'MinitutorsController@acceptRequest')->name('request.accept');
    Route::put('request/{id}/reject', 'MinitutorsController@rejectRequest')->name('request.reject');

    Route::get('{id}/videos', 'MinitutorsController@showVideos')->name('show.videos');
    Route::get('{id}/articles', 'MinitutorsController@showArticles')->name('show.articles');
    Route::get('{id}/followers', 'MinitutorsController@showFollowers')->name('show.followers');
    Route::get('{id}/comments', 'MinitutorsController@showComments')->name('show.comments');
    Route::get('{id}/feedback', 'MinitutorsController@showFeedback')->name('show.feedback');
});
Route::resource('minitutors', 'MinitutorsController')->except(['create', 'store']);



// manage requested article
Route::get('request-articles/{id}/accept', 'RequestArticlesController@accept')->name('request-articles.accept');
Route::resource('request-articles', 'RequestArticlesController')->only(['index', 'show', 'destroy']);


// manage article
Route::get('articles/minitutors', 'ArticlesController@minitutors')->name('articles.minitutors');
Route::post('articles/{id}/image', 'ArticlesController@uploadImage')->name('articles.upload.image');
Route::resource('articles', 'ArticlesController')->except('show');


// manage requested video
Route::get('request-videos/{id}/accept', 'RequestVideosController@accept')->name('request-videos.accept');
Route::resource('request-videos', 'RequestVideosController')->only(['index', 'show', 'destroy']);


// manage video
Route::get('videos/minitutors', 'VideosController@minitutors')->name('videos.minitutors');
Route::post('videos/{id}/upload-video', 'VideosController@uploadVideo')->name('videos.upload.video');
Route::resource('videos', 'VideosController')->except('show');


// manage comments
Route::get('comments/{id}/make-public', 'CommentsController@makePublic')->name('comments.make-public');
Route::resource('comments', 'CommentsController')->only(['index', 'destroy']);


// Handele Froala fileManager
Route::get('froala/image', 'FroalaController@getImage')->name('froala.image');
Route::post('froala/image', 'FroalaController@uploadImage');
Route::delete('froala/image', 'FroalaController@destroyImage');


// manage email
Route::get('emails', 'EmailsController@index')->name('emails.index');
Route::get('emails/broadcast', 'EmailsController@broadcast')->name('emails.broadcast');
Route::post('emails/broadcast', 'EmailsController@sendBroadcastEmails');
Route::get('emails/private', 'EmailsController@private')->name('emails.private');
Route::post('emails/private', 'EmailsController@sendPrivateEmail');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('guest')->group(function(){
    Route::get('/login', 'AuthController@showLoginForm')->name('login');
    Route::post('/login', 'AuthController@login');
});

Route::middleware('auth')->post('/logout', 'AuthController@logout')->name('logout');

Route::get('/', 'RootController@index')->name('root');

app/Models/User.php
<?php

namespace App\Models;

use App\Helpers\AvatarHelper;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;
use Tymon\JWTAuth\Contracts\JWTSubject;

class User extends Authenticatable implements JWTSubject
{
    use HasFactory, Notifiable, HasRoles;

    protected $fillable = [
        'name',
        'avatar',
        'points',
        'about',
        'website',
        'username',
        'email',
        'password',
        'email_notification',
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    public function getJWTCustomClaims()
    {
        return [];
    }

    public function minitutor()
    {
        return $this->hasOne(Minitutor::class);
    }

    public function joinMinitutor()
    {
        return $this->hasOne(JoinMinitutor::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function feedback()
    {
        return $this->hasMany(Feedback::class);
    }

    public function activities()
    {
        return $this->hasMany(Activity::class);
    }

    public function favorites()
    {
        return $this->hasMany(Favorite::class);
    }

    public function followings()
    {
        return $this->hasMany(Follow::class);
    }

    public function incrementPoint($point) {
        $this->points = $this->points + $point;
        return $this->save();
    }

    public function receivesBroadcastNotificationsOn(): String
    {
        return 'App.User.'.$this->id;
    }

    /**
     * Atributes
     */
    public function getAvatarUrlAttribute()
    {
        if(!$this->avatar) {
            return 'https://ui-avatars.com/api/?bold=true&background=f0f2fc&color=677ae4&size=120&name=' . $this->name;
        }
        return AvatarHelper::getUrl($this->avatar);
    }

    public function getFollowingIdsAttribute()
    {
        return $this->followings()->select('minitutor_id')->whereHas('minitutor', function ($q) {
            $q->where('active', true);
        })->get()->map(function ($item){
            return $item->minitutor_id;
        });
    }

    public function getFavoriteIdsAttribute()
    {
        return $this->favorites()->select('post_id')->whereHas('post', function ($q) {
            $q->whereNotNull('posted_at');
        })->get()->map(function ($item){
            return $item->post_id;
        });
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helpers\AvatarHelper;
use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\Minitutor;
use App\Rules\RoleExists;
use App\Rules\Username;
use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;
use Hash;

class UsersController extends Controller
{
    const EDUCATIONS = ['D1', 'D2', 'D3', 'S1', 'S2', 'S3'];

    public function __construct()
    {
        $this->middleware('can:manage user');
    }

    public function index(Request $request)
    {
        if (!empty($request->input('search'))) {
            $search = '%' . $request->input('search') . '%';
            $users = User::where('name', 'like', $search);
            $users->orWhere('username', 'like', $search);
            $users->orWhere('email', 'like', $search);
        } else {
            $users = User::orderBy('id', 'desc');
        }
        $users = $users->paginate(20)->appends(['search' => $request->input('search')]);
        return view('users.index', ['users' => $users]);
    }

    public function create()
    {
        $roles = Role::where('name', '!=', 'Super Admin')->get();
        return view('users.create', ['roles' => $roles]);
    }

    public function store(Request $request)
    {
        $data = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'username' => ['required', 'string', new Username, 'max:64', 'min:6', 'unique:users'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8'],
            'email_notification' => ['nullable'],
            'role' => ['nullable', 'integer', new RoleExists],
            'image' => 'nullable|image|max:4000',
        ]);

        $data['username'] = strtolower($data['username']);
        $data['password'] = Hash::make($data['password']);

        $data['email_notification'] = isset($data['email_notification']) ? true : false;

        if (isset($data['image'])) {
            $data['avatar'] = AvatarHelper::generate($data['image']);
            unset($data['image']);
        }

        $user = User::create($data);

        if (isset($data['role']) && $request->user()->can('manage role')) {
            $role = Role::findOrFail($data['role']);
            $user->assignRole($role->name);
        }

        return redirect()->route('users.edit', $user->id)->withSuccess('User telah dibuat.');
    }

    public function show($id)
    {
        $user = User::with('activities.post')->findOrFail($id);
        return view('users.show', ['user' => $user]);
    }


    public function showFavorites($id)
    {
        $user = User::with('favorites.post.minitutor.user')->findOrFail($id);
        return view('users.favorites', ['user' => $user ]);
    }

    public function showFollowings($id)
    {
        $user = User::with('followings.minitutor.user')->findOrFail($id);
        return view('users.followings', ['user' => $user]);
    }

    public function edit($id)
    {
        $user = User::findOrFail($id);
        $roles = Role::where('name', '!=', 'Super Admin')->get();
        return view('users.edit', ['user' => $user, 'roles' => $roles]);
    }

    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id);

        $data = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'username' => ['required', 'string', new Username, 'max:64', 'min:6', 'unique:users,username,' . $id],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users,email,' . $id],
            'password' => ['nullable', 'string', 'min:8'],
            'email_notification' => ['nullable'],
            'role' => ['nullable', 'integer', new RoleExists],
            'image' => 'nullable|image|max:4000',
            'website' => ['nullable', 'url', 'max:250'],
        ]);

        if (!$user->hasRole('Super Admin') && $request->user()->can('manage role')) {
            if (isset($data['role'])) {
                $role = Role::findOrFail($data['role']);
                $user->syncRoles($role->name);
            } else {
                $user->syncRoles([]);
            }
        }

        $data['username'] = strtolower($data['username']);

        if ($data['password']) {
            $data['password'] = Hash::make($data['password']);
        } else {
            unset($data['password']);
        }

        if (isset($data['image'])) {
            $data['avatar'] = AvatarHelper::generate($data['image']);
            AvatarHelper::destroy($user->avatar);
            unset($data['image']);
        }

        $data['email_notification'] = isset($data['email_notification']) ? true : false;

        $user->update($data);
        return redirect()->back()->withSuccess('User telah diperbarui.');
    }

    public function destroy($id)
    {
        $user = User::findOrFail($id);
        if ($user->hasRole('Super Admin')) {
            return abort(403);
        }
        AvatarHelper::destroy($user->avatar);
        $user->delete();
        return redirect()->route('users.index')->withSuccess('User telah dihapus.');
    }


    public function createMinitutor($id)
    {
        $user = User::findOrFail($id);
        if (isset($user->minitutor)) {
            return abort(404);
        }
        return view('users.create_minitutor', ['user' => $user, 'last_educations' => self::EDUCATIONS]);
    }

    public function storeMinitutor(Request $request, $id)
    {
        $user = User::findOrFail($id);
        if (isset($user->minitutor)) {
            return abort(404);
        }

        $data = $request->validate([
            'last_education' => 'required|string|max:50',
            'university' => 'required|string|max:250',
            'city_and_country_of_study' => 'required|string|max:250',
            'majors' => 'required|string|max:250',
            'contact' => 'required|string|max:250',
        ]);
        $data['interest_talent'] = '';
        $data['reason'] = '';
        $data['expectation'] = '';
        $data['active'] = true;
        $minitutor = new Minitutor($data);
        $user->minitutor()->save($minitutor);
        return redirect()->route('minitutors.show', $minitutor->id)->withSuccess('Berhasil mejadikan user sebagai minitutor.');
    }
}

app/Http/Controllers/Api/App/UsersController.php
<?php

namespace App\Http\Controllers\Api\App;

use App\Http\Controllers\Controller;
use App\Http\Resources\PostResource;
use App\Http\Resources\UserResource;
use App\Http\Resources\MinitutorResource;
use App\Models\Post;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

class UsersController extends Controller
{
    public function index(Request $request)
    {
        $users = Cache::remember('users.page.' . $request->input('page') ?? 1, config('cache.age'), function () {
            return UserResource::collection(User::orderBy('points', 'desc')->orderBy('id')->paginate(20));
        });
        return $users;
    }

    public function show($id)
    {
        $user = User::where('id', $id)->orWhere('username', $id)->firstOrFail();
        $data = [
            'user' => UserResource::make($user),
            'favorites' => $user->favorites()->with(['post' => function($q){
                return Post::postListQuery($q);
            }])->get()->map(function($item){
                return [
                    'id' => $item->id,
                    'created_at' => $item->created_at,
                    'post' => PostResource::make($item->post)
                ];
            }),
            'followings' => $user->followings()->with(['minitutor' => function($q){
                return $q->where('active', true)->with('user');
            }])->get()->map(function($item){
                return [
                    'id' => $item->id,
                    'created_at' => $item->created_at,
                    'user' => UserResource::make($item->minitutor->user),
                    'minitutor' => MinitutorResource::make($item->minitutor),
                ];
            })
        ];
        return $data;
    }

    public function mostPoints()
    {
        $users = Cache::remember('users.most.points', config('cache.age'), function () {
            return UserResource::collection(User::orderBy('points', 'desc')->limit(8)->get());
        });
        return $users;
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')
  <div class="container-fluid">
    <div class="card">
      <div class="card-header d-flex">
        <h3>Buat User</h3>
        <div class="my-auto ml-auto">
          <a href="{{ route('users.index') }}" class="btn btn-sm btn-primary">Batal</a>
        </div>
      </div>
      <div class="card-body">
        <form action="{{ route('users.store') }}" method="post" enctype="multipart/form-data">
          @csrf

          @can('manage role')
            <div class="form-group">
              <label for="role">Role</label>
              <select class="form-control @error('role') is-invalid @enderror" name="role" id="role">
                <option value="">Bukan Admin</option>
                @foreach ($roles as $role)
                  <option value="{{ $role->id }}" @if (old('role') == $role->id) selected @endif>{{ $role->name }}</option>
                @endforeach
              </select>
              @error('role')
                <span class="invalid-feedback">{{ $message }}</span>
              @enderror
            </div>
          @endcan

          <div class="form-group">
            <label>Nama</label>
            <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" placeholder="Nama..." value="{{ old('name') }}">
            @error('name')
              <span class="invalid-feedback">{{ $message }}</span>
            @enderror
          </div>

          <div class="form-group">
            <label>Username</label>
            <input type="text" class="form-control @error('username') is-invalid @enderror" name="username" placeholder="Username..." value="{{ old('username') }}">
            @error('username')
              <span class="invalid-feedback">{{ $message }}</span>
            @enderror
          </div>

          <div class="form-group">
            <label>Email</label>
            <input type="text" class="form-control @error('email') is-invalid @enderror" name="email" placeholder="Email..." value="{{ old('email') }}">
            @error('email')
              <span class="invalid-feedback">{{ $message }}</span>
            @enderror
          </div>

          <div class="form-group">
            <label>Password</label>
            <input type="text" class="form-control @error('password') is-invalid @enderror" name="password" placeholder="Password..." value="{{ old('password') }}">
            @error('password')
              <span class="invalid-feedback">{{ $message }}</span>
            @enderror
          </div>

          <div class="form-group">
            <label>Avatar</label>
            <div class="custom-file">
              <input type="file" class="custom-file-input" name="image" id="custom-input-avatar" accept="image/*">
              <label class="custom-file-label @error('image') border-danger @enderror" for="custom-input-avatar">Pilih Gambar</label>
            </div>
            @error('image')
              <span class="invalid-feedback d-block">{{ $message }}</span>
            @enderror
          </div>

          <div class="form-group">
            <div class="form-check">
              <input type="checkbox" class="form-check-input" id="email_notification" name="email_notification" @if (old('email_notification')) checked @endif>
              <label for="email_notification">Email Notifikasi</label>
            </div>
          </div>

          <div class="form-group">
            <button type="submit" class="btn btn-primary">Buat User</button>
          </div>
        </form>
      </div>
    </div>
  </div>
@endsection

resources/views/users/create_minitutor.blade.php
@extends('layouts.app')

@section('content')
  <div class="container-fluid">
    <div class="card">
      <div class="card-header d-flex">
        <h3>Buat MiniTuor</h3>
        <div class="my-auto ml-auto">
          <a href="{{ route('users.index') }}" class="btn btn-sm btn-primary">Batal</a>
        </div>
      </div>
      <div class="card-body">
        <form action="{{ route('users.minitutor.store', $user->id) }}" method="post">
          @csrf

          <div class="form-group">
            <label>Pendidikan terakhir</label>
            <select name="last_education" class="form-control @error('last_education') is-invalid @enderror">
              <option value="" disabled @if(!old('last_education')) selected @endif>Pendidikan terakhir</option>
              @foreach($last_educations as $education)
              <option value="{{ $education }}" @if(old('last_education') === $education) selected @endif>{{ $education }}</option>
              @endforeach
            </select>
            @error('last_education')
            <div class="invalid-feedback">
              <strong>{{ $message }}</strong>
            </div>
            @enderror
          </div>

          <div class="form-group">
            <label>Nama Kampus</label>
            <input name="university" placeholder="Nama Kampus" type="text" class="form-control @error('university') is-invalid @enderror" value="{{ old('university') }}">
            @error('university')
              <div class="invalid-feedback">
                <strong>{{ $message }}</strong>
              </div>
            @enderror
          </div>

          <div class="form-group">
            <label>Kota dan Negara Kampus</label>
            <input name="city_and_country_of_study" placeholder="Kota dan Negara Kampus" type="text" class="form-control @error('city_and_country_of_study') is-invalid @enderror" value="{{ old('city_and_country_of_study') }}">
            @error('city_and_country_of_study')
              <div class="invalid-feedback">
                <strong>{{ $message }}</strong>
              </div>
            @else
              <span class="text-help">Contoh: Jakatarta, Indonesia</span>
            @enderror
          </div>

          <div class="form-group">
            <label>Jurusan</label>
            <input name="majors" placeholder="Jurusan" type="text" class="form-control @error('majors') is-invalid @enderror" value="{{ old('majors') }}">
            @error('majors')
              <div class="invalid-feedback">
                <strong>{{ $message }}</strong>
              </div>
            @enderror
          </div>

          <div class="form-group">
            <label>No.HP (whatsapp)</label>
            <input name="contact" placeholder="No.HP (whatsapp only)" type="text" class="form-control @error('contact') is-invalid @enderror" value="{{ old('contact') }}">
            @error('contact')
              <div class="invalid-feedback">
                <strong>{{ $message }}</strong>
              </div>
            @enderror
          </div>

          <div class="form-group">
            <button type="submit" class="btn btn-primary">Buat MiniTutor</button>
          </div>
        </form>
      </div>
    </div>
  </div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
  <x-user-wrapper :user="$user">
    <form action="{{ route('users.update', $user->id) }}" method="post" class="d-block p-3" enctype="multipart/form-data">
      @csrf
      @method('put')
      @can('manage role')
        @if (!$user->hasRole('Super Admin'))
          <div class="form-group">
            <label for="role">Role</label>
            <select class="form-control @error('role') is-invalid @enderror" name="role" id="role">
              <option value="">Bukan Admin</option>
              @foreach ($roles as $role)
                @php
                  if (count($user->roles)) {
                      $role_id = $user->roles[0]->id;
                  } else {
                      $role_id = 0;
                  }
                @endphp
                <option value="{{ $role->id }}" @if ($role_id == $role->id) selected @endif>{{ $role->name }}</option>
              @endforeach
            </select>
            @error('role')
              <span class="invalid-feedback">{{ $message }}</span>
            @enderror
          </div>
        @endif
      @endcan

      <div class="form-group">
        <label>Nama</label>
        <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" placeholder="Nama ..." value="{{ $user->name }}">
        @error('name')
          <span class="invalid-feedback">{{ $message }}</span>
        @enderror
      </div>

      <div class="form-group">
        <label>Username</label>
        <input type="text" class="form-control @error('username') is-invalid @enderror" name="username" placeholder="Username..." value="{{ $user->username }}">
        @error('username')
          <span class="invalid-feedback">{{ $message }}</span>
        @enderror
      </div>

      <div class="form-group">
        <label>Email</label>
        <input type="text" class="form-control @error('email') is-invalid @enderror" name="email" placeholder="Email..." value="{{ $user->email }}">
        @error('email')
          <span class="invalid-feedback">{{ $message }}</span>
        @enderror
      </div>

      <div class="form-group">
        <label>Password</label>
        <input type="text" class="form-control @error('password') is-invalid @enderror" name="password" placeholder="Password..." value="{{ old('password') }}">
        @error('password')
          <span class="invalid-feedback">{{ $message }}</span>
        @enderror
      </div>

      <div class="form-group">
        <label>Website</label>
        <input type="text" class="form-control @error('website') is-invalid @enderror" name="website" placeholder="Website..." value="{{ $user->website }}">
        @error('website')
          <span class="invalid-feedback">{{ $message }}</span>
        @enderror
      </div>


      <div class="form-group">
        <label>Avatar</label>
        <div class="custom-file">
          <input type="file" class="custom-file-input" name="image" id="custom-input-avatar" accept="image/*">
          <label class="custom-file-label @error('image') border-danger @enderror" for="custom-input-avatar">Pilih Gambar</label>
        </div>
        @error('image')
          <span class="invalid-feedback d-block">{{ $message }}</span>
        @enderror
      </div>

      <div class="form-group">
        <div class="form-check">
          <input type="checkbox" class="form-check-input" id="email_notification" name="email_notification" @if ($user->email_notification) checked @endif>
          <label for="email_notification">Email Notifikasi</label>
        </div>
      </div>

      <div class="form-group">
        <button type="submit" class="btn btn-primary">Edit User</button>
      </div>
    </form>
  </x-user-wrapper>
@endsection

resources/views/users/favorites.blade.php
@extends('layouts.app')

@section('content')
  <x-user-wrapper :user="$user">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Tipe</th>
          <th>Judul</th>
          <th>Waktu</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($user->favorites as $favorite)
          <tr>
            <td class="font-weight-bold align-middle">{{ $favorite->post->type }}</td>
            <td class="align-middle">{{ $favorite->post->title }}</td>
            <td class="align-middle">{{ $favorite->created_at->diffForhumans() }}</td>
          </tr>
        @endforeach
      </tbody>
    </table>
  </x-user-wrapper>
@endsection

resources/views/users/followings.blade.php
@extends('layouts.app')

@section('content')
  <x-user-wrapper :user="$user">

    <table class="table table-hover">
      <thead>
        <tr>
          <th>Avatar</th>
          <th>Nama</th>
          <th>Username</th>
          <th>Email</th>
          <th>Waktu</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($user->followings as $item)
          <tr>
            <td class="align-middle">
              <span class="avatar">
                <img width="30px" src="{{ $item->minitutor->user->avatar_url }}" />
              </span>
            </td>
            <td class="align-middle"><a href="{{ route('minitutors.show', $item->minitutor->id) }}">{{ $item->minitutor->user->name }}</a></td>
            <td class="align-middle">{{ $item->minitutor->user->username }}</td>
            <td class="align-middle">{{ $item->minitutor->user->email }}</td>
          </tr>
        @endforeach
      </tbody>
    </table>
  </x-user-wrapper>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
  <div class="card">
    <div class="card-header d-flex">
      <h3>User</h3>
      <div class="ml-auto my-auto">
        <a href="{{ route('users.create') }}" class="btn btn-sm btn-primary">Buat User</a>
      </div>
    </div>
    <div class="card-body">
      <div class="form-group">
        <form method="get" class="input-group">
          <input type="text" class="form-control" name="search" placeholder="Search..." value="{{ request()->input('search') }}">
          <span class="input-group-append">
            <button type="submit" class="btn btn-primary"><i class="fas fa-search"></i></button>
          </span>
        </form>
      </div>
    </div>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Avatar</th>
          <th>Nama</th>
          <th>Poin</th>
          <th>Username</th>
          <th>Email</th>
          <th class="text-center" style="width: 140px;">Aksi</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($users as $user)
          <tr>
            <td class="align-middle">
              <span class="avatar">
                <img width="30px" src="{{ $user->avatar_url }}" />
              </span>
            </td>
            <td class="align-middle"><a href="{{ route('users.show', $user->id) }}">{{ $user->name }}</a></td>
            <td class="align-middle">{{ $user->points }}</td>
            <td class="align-middle">{{ $user->username }}</td>
            <td class="align-middle">{{ $user->email }}</td>
            <td class="text-center py-0 align-middle">
              <a href="{{ route('users.show', $user->id) }}" class="btn btn-default btn-sm"><i class="fas fa-eye"></i></a>
              <a href="{{ route('users.edit', $user->id) }}" class="btn btn-default btn-sm"><i class="fas fa-edit"></i></a>
              <button class="btn btn-danger btn-sm btn-icon" delete-confirm="#form-delete-user-{{ $user->id }}">
                <i class="fas fa-trash"></i>
              </button>
              <form action="{{ route('users.destroy', $user->id) }}" method="post" id="form-delete-user-{{ $user->id }}">
                @csrf
                @method('delete')
              </form>
            </td>
          </tr>
        @endforeach
      </tbody>
    </table>
    <div class="card-footer">
      {{ $users->links() }}
    </div>
  </div>
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')

@section('content')
  <x-user-wrapper :user="$user">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Tipe</th>
          <th>Judul</th>
          <th>Waktu</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($user->activities as $activity)
          <tr>
            <td class="font-weight-bold">{{ $activity->post->type }}</td>
            <td>{{ $activity->post->title }}</td>
            <td>{{ $activity->updated_at->diffForhumans() }}</td>
          </tr>
        @endforeach
      </tbody>
    </table>
  </x-user-wrapper>
@endsection