routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

// admin access
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

// Profile
Route::get('profile', 'ProfileController@index')->name('profile.index');
Route::get('profile/logout', 'ProfileController@logout')->name('profile.logout');


// manage permission
Route::resource('permissions', 'PermissionsController')->except(['show']);


// manage role
Route::get('roles/toggle-sync-permission/{role_id}/{permission_id}', 'RolesController@toggleSyncPermission')->name('roles.toggle.sync.permission');
Route::resource('roles', 'RolesController')->except(['show']);


// manage user
Route::prefix('users/{id}/minitutor')->as('users.minitutor.')->group(function(){
    Route::get('/create', 'UsersController@createMinitutor')->name('create');
    Route::post('/', 'UsersController@storeMinitutor')->name('store');
});
Route::get('users/{id}/followings', 'UsersController@showFollowings')->name('users.show.followings');
Route::get('users/{id}/favorites', 'UsersController@showFavorites')->name('users.show.favorites');
Route::resource('users', 'UsersController');


// manage minitutor
Route::prefix('minitutors')->as('minitutors.')->group(function(){
    Route::get('{id}/active-toggle', 'MinitutorsController@activeToggle')->name('active.toggle');
    Route::get('requests', 'MinitutorsController@requests')->name('requests');
    Route::get('request/{id}', 'MinitutorsController@showRequest')->name('request.show');
    Route::put('request/{id}/accept', 'MinitutorsController@acceptRequest')->name('request.accept');
    Route::put('request/{id}/reject', 'MinitutorsController@rejectRequest')->name('request.reject');

    Route::get('{id}/videos', 'MinitutorsController@showVideos')->name('show.videos');
    Route::get('{id}/articles', 'MinitutorsController@showArticles')->name('show.articles');
    Route::get('{id}/followers', 'MinitutorsController@showFollowers')->name('show.followers');
    Route::get('{id}/comments', 'MinitutorsController@showComments')->name('show.comments');
    Route::get('{id}/feedback', 'MinitutorsController@showFeedback')->name('show.feedback');
});
Route::resource('minitutors', 'MinitutorsController')->except(['create', 'store']);



// manage requested article
Route::get('request-articles/{id}/accept', 'RequestArticlesController@accept')->name('request-articles.accept');
Route::resource('request-articles', 'RequestArticlesController')->only(['index', 'show', 'destroy']);


// manage article
Route::get('articles/minitutors', 'ArticlesController@minitutors')->name('articles.minitutors');
Route::post('articles/{id}/image', 'ArticlesController@uploadImage')->name('articles.upload.image');
Route::resource('articles', 'ArticlesController')->except('show');


// manage requested video
Route::get('request-videos/{id}/accept', 'RequestVideosController@accept')->name('request-videos.accept');
Route::resource('request-videos', 'RequestVideosController')->only(['index', 'show', 'destroy']);


// manage video
Route::get('videos/minitutors', 'VideosController@minitutors')->name('videos.minitutors');
Route::post('videos/{id}/upload-video', 'VideosController@uploadVideo')->name('videos.upload.video');
Route::resource('videos', 'VideosController')->except('show');


// manage comments
Route::get('comments/{id}/make-public', 'CommentsController@makePublic')->name('comments.make-public');
Route::resource('comments', 'CommentsController')->only(['index', 'destroy']);


// Handele Froala fileManager
Route::get('froala/image', 'FroalaController@getImage')->name('froala.image');
Route::post('froala/image', 'FroalaController@uploadImage');
Route::delete('froala/image', 'FroalaController@destroyImage');


// manage email
Route::get('emails', 'EmailsController@index')->name('emails.index');
Route::get('emails/broadcast', 'EmailsController@broadcast')->name('emails.broadcast');
Route::post('emails/broadcast', 'EmailsController@sendBroadcastEmails');
Route::get('emails/private', 'EmailsController@private')->name('emails.private');
Route::post('emails/private', 'EmailsController@sendPrivateEmail');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('guest')->group(function(){
    Route::get('/login', 'AuthController@showLoginForm')->name('login');
    Route::post('/login', 'AuthController@login');
});

Route::middleware('auth')->post('/logout', 'AuthController@logout')->name('logout');

Route::get('/', 'RootController@index')->name('root');

app/Models/User.php
<?php

namespace App\Models;

use App\Helpers\AvatarHelper;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;
use Tymon\JWTAuth\Contracts\JWTSubject;

class User extends Authenticatable implements JWTSubject
{
    use HasFactory, Notifiable, HasRoles;

    protected $fillable = [
        'name',
        'avatar',
        'points',
        'about',
        'website',
        'username',
        'email',
        'password',
        'email_notification',
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    public function getJWTCustomClaims()
    {
        return [];
    }

    public function minitutor()
    {
        return $this->hasOne(Minitutor::class);
    }

    public function joinMinitutor()
    {
        return $this->hasOne(JoinMinitutor::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function feedback()
    {
        return $this->hasMany(Feedback::class);
    }

    public function activities()
    {
        return $this->hasMany(Activity::class);
    }

    public function favorites()
    {
        return $this->hasMany(Favorite::class);
    }

    public function followings()
    {
        return $this->hasMany(Follow::class);
    }

    public function incrementPoint($point) {
        $this->points = $this->points + $point;
        return $this->save();
    }

    public function receivesBroadcastNotificationsOn(): String
    {
        return 'App.User.'.$this->id;
    }

    /**
     * Atributes
     */
    public function getAvatarUrlAttribute()
    {
        if(!$this->avatar) {
            return 'https://ui-avatars.com/api/?bold=true&background=f0f2fc&color=677ae4&size=120&name=' . $this->name;
        }
        return AvatarHelper::getUrl($this->avatar);
    }

    public function getFollowingIdsAttribute()
    {
        return $this->followings()->select('minitutor_id')->whereHas('minitutor', function ($q) {
            $q->where('active', true);
        })->get()->map(function ($item){
            return $item->minitutor_id;
        });
    }

    public function getFavoriteIdsAttribute()
    {
        return $this->favorites()->select('post_id')->whereHas('post', function ($q) {
            $q->whereNotNull('posted_at');
        })->get()->map(function ($item){
            return $item->post_id;
        });
    }
}

app/Http/Controllers/Admin/VideosController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helpers\CategoryHelper;
use App\Helpers\VideoHelper;
use App\Helpers\HeroHelper;
use App\Helpers\PointHelper;
use App\Http\Controllers\Controller;
use App\Models\Post;
use App\Models\Category;
use App\Models\Image;
use App\Models\Minitutor;
use App\Notifications\MinitutorPostPublishedNotification;
use App\Notifications\NewPostNotification;
use Exception;
use Illuminate\Http\Request;

class VideosController extends Controller
{
    public function __construct()
    {
        $this->middleware('can:manage video');
    }

    public function index(Request $request)
    {
        if (!empty($request->input('search'))) {
            $search = '%' . $request->input('search') . '%';
            $videos = Post::where('type', 'video')->where('title', 'like', $search);
        } else {
            $videos = Post::where('type', 'video');
        }
        $videos = $videos->orderBy('id', 'desc')->paginate(20)->appends(['search' => $request->input('search')]);
        return view('videos.index', ['videos' => $videos]);
    }

    public function minitutors(Request $request)
    {
        if (!empty($request->input('search'))) {
            $search = '%' . $request->input('search') . '%';
            $minitutors = Minitutor::whereHas('user', function ($q) use ($search) {
                return $q->where('name', 'like', $search)
                    ->orWhere('username', 'like', $search)
                    ->orWhere('email', 'like', $search);
            })->where('active', true)->orderBy('id', 'desc');
        } else {
            $minitutors = Minitutor::where('active', true)->orderBy('id', 'desc');
        }
        $minitutors = $minitutors->paginate(20)->appends(['search' => $request->input('search')]);
        return view('videos.minitutors', ['minitutors' => $minitutors]);
    }

    public function create(Request $request)
    {
        $minitutor = Minitutor::where('active', true)->findOrFail($request->input('id') ?? 0);
        return view('videos.create', ['minitutor' => $minitutor]);
    }

    public function store(Request $request)
    {
        $minitutor = Minitutor::where('active', true)->findOrFail($request->input('id') ?? 0);

        $data = $request->validate([
            'title' => 'required|string|min:6|max:250',
            'description' => 'nullable'
        ]);

        $data['type'] = 'video';
        $video = new Post($data);
        $minitutor->posts()->save($video);

        PointHelper::onMinitutorPostCreated($minitutor->user);

        return redirect()->route('videos.edit', $video->id)->withSuccess('Video telah dibuat.');
    }

    public function edit($id)
    {
        $video = Post::where('type', 'video')->findOrFail($id);
        $categories = Category::all();
        return view('videos.edit', ['video' => $video, 'categories' => $categories]);
    }

    public function uploadVideo(Request $request, $id)
    {
        $video = Post::where('type', 'video')->findOrFail($id);
        $data = $request->validate(['file' => 'required|mimes:mp4,mov,avi,fly|max:500000']);
        $upload = VideoHelper::upload($data['file'], $video->body);
        $video->body = $upload;
        $video->save();
        return response()->noContent();
    }

    public function update(Request $request, $id)
    {
        $video = Post::where('type', 'video')->findOrFail($id);
        $data = $request->validate([
            'title' => 'required|string|min:6|max:250',
            'description' => 'nullable',
            'category' => 'nullable|string',
            'hero' => 'nullable|image|max:4000'
        ]);

        if (isset($data['hero'])) {
            $data['hero'] = HeroHelper::generate($data['hero'], $video->hero);
        } else {
            unset($data['hero']);
        }

        if (isset($data['category'])) {
            $data['category_id'] = Category::getCategoryOrCreate($data['category'])->id;
        } else {
            $data['category_id'] = null;
        }
        unset($data['category']);

        $public = (bool) $request->input('public');

        if(!$public && $video->posted_at) {
            $data['posted_at'] = null;
        }

        if($public && !$video->posted_at) {
            $data['posted_at'] = now();

            $video->minitutor->user->notify(new MinitutorPostPublishedNotification($video));
            foreach($video->minitutor->followers()->get() as $follower){
                try {
                    $follower->user->notify(new NewPostNotification($video));
                } catch(Exception $e) {
                    continue;
                }
            }
        }

        $video->update($data);
        return redirect()->back()->withSuccess('Video telah diperbarui.');
    }

    public function destroy($id)
    {
        $video = Post::where('type', 'video')->findOrFail($id);
        foreach($video->images as $image) {
            EditorjsHelper::deleteImage($image->name);
            $image->delete();
        }
        HeroHelper::destroy($video->hero);
        $video->delete();
        return redirect()->route('videos.index')->withSuccess('Video berhasil dihapus.');
    }
}

app/Http/Controllers/Api/App/VideosController.php
<?php

namespace App\Http\Controllers\Api\App;

use App\Jobs\AfterViewPostJob;
use App\Http\Controllers\Controller;
use App\Http\Resources\PostResource;
use App\Http\Resources\VideoResource;
use App\Models\Post;
use Illuminate\Http\Request;
use Cache, DB;

class VideosController extends Controller
{
    public function index(Request $request)
    {
        return Cache::remember('videos.page.' . $request->input('page') ?? 1, config('cache.age'), function () {
            $videos = Post::postListQuery(Post::where('type', 'video'))->orderBy('id', 'desc')->paginate(12);
            return PostResource::collection($videos);
        });
    }

    public function show($slug)
    {
        $data = Cache::remember('videos.show.' . $slug, config('cache.age'), function () use ($slug) {
            $query = Post::whereNotNull('posted_at')->where('type', 'video');
            $query->with(['category']);
            $query->with(['minitutor' => function ($q) {
                $q->with(['user' => function ($q) {
                    $q->select([ 'id', 'name', 'avatar', 'points', 'username' ]);
                }]);
            }]);
            $query->with(['comments' => function ($q) {
                $q->with(['user' => function ($q) {
                    $q->select([ 'id', 'name', 'avatar', 'points', 'username' ]);
                }]);
                $q->where('public', true);
            }]);
            $query->withCount('activities as view_count');
            $query->withCount(['feedback as rating' => function ($q) {
                $q->select(DB::raw('coalesce(avg((understand + inspiring + language_style + content_flow)/4),0)'));
            }, 'feedback']);
            $query->whereHas('minitutor', function ($q) {
                $q->where('active', true);
            });
            $video = $query->where('slug', $slug)->firstOrFail();

            $latesPosts = $video->minitutor
                ->posts()
                ->whereNotNull('posted_at')
                ->where('id', '!=', $video->id)
                ->take(8)
                ->get()
                ->map(function($item){
                return [
                    'id' => $item->id,
                    'type' => $item->type,
                    'title' => $item->title,
                    'slug' => $item->slug,
                    'posted_at' => $item->posted_at,
                ];
            });

            return [
                'video' => VideoResource::make($video),
                'latesPosts' => $latesPosts,
            ];
        });
        AfterViewPostJob::dispatchAfterResponse($data['video'], auth('api')->user());
        return $data;
    }

    public function news()
    {
        $videos = Cache::remember('videos.news', config('cache.age'), function () {
            $videos = Post::postListQuery(Post::where('type', 'video'))->orderBy('posted_at', 'desc')->limit(8)->get();
            return PostResource::collection($videos);
        });
        return $videos;
    }
}

resources/views/videos/create.blade.php
@extends('layouts.app')

@section('content')
  <div class="container-fluid">
    <div class="card">
      <div class="card-header d-flex">
        <h3>Buat Video</h3>
        <div class="my-auto ml-auto">
          <a href="{{ route('videos.minitutors') }}" class="btn btn-sm btn-primary">Batal</a>
        </div>
      </div>
      <div class="card-body">
        <form action="{{ route('videos.store', ['id' => $minitutor->id]) }}" method="post">
          @csrf

          <div class="form-group">
            <label for="title">Judul</label>
            <input type="text" name="title" id="title" class="form-control @error('title') is-invalid @enderror" value="{{ old('title') }}">
            @error('title')
              <span class="invalid-feedback font-weight-bold">{{ $message }}</span>
            @enderror
          </div>

          <div class="form-group">
            <label for="description">Deskripsi</label>
            <textarea name="description" id="description" class="form-control @error('description') is-invalid @enderror">{{ old('description') }}</textarea>
            @error('description')
              <span class="invalid-feedback font-weight-bold">{{ $message }}</span>
            @enderror
          </div>

          <div class="form-group">
            <button type="submit" class="btn btn-primary">Buat Video</button>
          </div>
        </form>
      </div>
    </div>
  </div>
@endsection

resources/views/videos/edit.blade.php
@extends('layouts.app')

@section('script:after')
  <script>
    $(function() {
      window.initAutocomplete('autoComplete', {!! json_encode($categories) !!}, ["name"])

      const $error = $('#upload-error')
      const $name = $('#upload-name')
      const $message = $('#upload-message')
      const $toggle = $('#upload-toggle')
      const $input = $('#video-input')

      $toggle.on('click', function() {
        $input.click()
      })

      $input.on('change', function(e) {
        const file = e.target.files ? e.target.files[0] : null
        if (file) {
          const data = new window.FormData()
          data.append('file', file)

          $error.addClass('d-none')
          $toggle.addClass('d-none')

          $name.removeClass('d-none')
          $message.removeClass('d-none')

          $name.text('Sedang menupload ' + file.name)

          window.axios
            .post($input.attr('upload-url'), data, {
              onUploadProgress: function(ev) {
                var percentCompleted = Math.round((ev.loaded * 100) / ev.total)
                if (percentCompleted === 100) {
                  $name.text('Video anda sedang diproses...')
                } else {
                  $name.text('Mengupload total ' + percentCompleted + '%')
                }
              }
            })
            .then((res) => {
              window.location.reload(true)
            })
            .catch(err => {
              $name.addClass('d-none')
              $message.addClass('d-none')

              $error.removeClass('d-none')

              let mess = ''
              if (err.response && err.response.data && err.response.data.message) {
                $error.text(err.response.data.message)
              } else {
                $error.text('Gagal mengupload file!')
              }
              $toggle.removeClass('d-none')
            })
        }
      })
    })
  </script>
@endsection

@section('content')
  <div class="container-fluid">
    <input type="file" class="d-none" id="video-input" accept="video/*" upload-url="{{ route('videos.upload.video', $video->id) }}">
    <form class="row" method="post" enctype="multipart/form-data" action="{{ route('videos.update', $video->id) }}">
      @csrf
      @method('PUT')
      <div class="col-lg-8">
        <div class="card">
          <div class="card-header">
            <strong>Body</strong>
          </div>
          <div class="card-body p-0">
            <div class="w-full">
              <video controls src="{{ $video->videoUrl }}" class="d-block w-100"></video>
            </div>
          </div>
          <div class="card-body">
            <p class="text-center text-danger d-none" id="upload-error"></p>
            <p class="text-center d-none" id="upload-name"></p>
            <p class="text-center d-none" id="upload-message"></p>
            <div class="text-center">
              <button class="btn btn-default" id="upload-toggle" type="button">PILIH VIDEO UNTUK DI UPLOAD</button>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="card">
          <div class="card-header px-3">
            <strong>Hero</strong>
          </div>
          <div class="card-body p-3">
            <img src="{{ $video->heroUrl['thumb'] ? $video->heroUrl['thumb'] : asset('img/placeholder/hero-thumb.jpg') }}" class="img-fluid d-block w-100" />
            <div class="form-group pt-2 m-0">
              <div class="custom-file">
                <input type="file" class="custom-file-input" name="hero" id="custom-input-avatar" accept="image/*">
                <label class="custom-file-label @error('hero') border-danger @enderror" for="custom-input-avatar">Pilih Gambar</label>
              </div>
              @error('hero')
                <span class="invalid-feedback d-block">{{ $message }}</span>
              @enderror
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-header px-3">
            <strong>Informasi</strong>
          </div>
          <div class="card-body p-3">
            <div class="category-autocomplete">
              <div class="form-group">
                <label>Kategori</label>
                <input ref="input" placeholder="Kategori" id="autoComplete" autocomplete="off" type="text" name="category" class="autocomplete form-control @error('category') is-invalid @enderror"
                  value="{{ old('category') ?? $video->category ? $video->category->name : '' }}">
                @error('category')
                  <div class="invalid-feedback">
                    <strong>{{ $message }}</strong>
                  </div>
                @enderror
              </div>
            </div>

            <div class="form-group">
              <label>Judul</label>
              <input placeholder="Judul" type="text" name="title" class="form-control @error('title') is-invalid @enderror" value="{{ old('title') ?? $video->title }}">
              @error('title')
                <div class="invalid-feedback">
                  <strong>{{ $message }}</strong>
                </div>
              @enderror
            </div>

            <div class="form-group">
              <label>Deskripsi</label>
              <textarea placeholder="Deskripsi" name="description" rows="3" class="form-control @error('description') is-invalid @enderror">{{ old('description') ?? $video->description }}</textarea>
              @error('description')
                <div class="invalid-feedback">
                  <strong>{{ $message }}</strong>
                </div>
              @enderror
            </div>

            <div class="form-group">
              <div class="checkbox-custom checkbox-primary">
                <input type="checkbox" id="public" name="public" @if (old('public') ?? (bool) $video->posted_at) checked @endif>
                <label for="public">Publikasikan artikel ini</label>
              </div>
            </div>

            <div class="form-group">
              <button type="submit" class="btn btn-primary">Simpan</button>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
@endsection

resources/views/videos/index.blade.php
@extends('layouts.app')

@section('content')
  <div class="container-fluid">
    <div class="card">
      <div class="card-header d-flex">
        <h3>Video</h3>
        <div class="my-auto ml-auto">
          <a href="{{ route('videos.minitutors') }}" class="btn btn-sm btn-primary">Buat Video</a>
        </div>
      </div>
      <div class="card-body">
        <div class="form-group">
          <form method="get" class="input-group">
            <input type="text" class="form-control" name="search" placeholder="Search..." value="{{ request()->input('search') }}">
            <span class="input-group-append">
              <button type="submit" class="btn btn-primary"><i class="fas fa-search"></i></button>
            </span>
          </form>
        </div>
      </div>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Judul</th>
            <th>Penulis</th>
            <th>Kategori</th>
            <th>Status</th>
            <th>Dibuat pada</th>
            <th class="text-center" style="width: 120px;">Aksi</th>
          </tr>
        </thead>
        <tbody>
          @foreach ($videos as $video)
            <tr>
              <td class="font-weight-bold align-middle">{{ $video->title }}</td>
              <td class="font-weight-bold align-middle">{{ $video->minitutor->user->name }}</td>
              <td class="font-weight-bold align-middle">{{ $video->category ? $video->category->name : '-' }}</td>
              <td class="font-weight-bold align-middle">{{ $video->posted_at ? 'Public' : 'Draf' }}</td>
              <td class="font-weight-bold align-middle">{{ $video->created_at }}</td>
              <td class="text-center py-0 align-middle">
                <a href="{{ route('videos.edit', $video->id) }}" class="btn btn-default btn-sm" title="Edit">
                  <i class="fas fa-edit"></i>
                </a>
                <button class="btn btn-danger btn-sm btn-icon" title="Delete" delete-confirm="#form-delete-video-{{ $video->id }}">
                  <i class="fas fa-trash"></i>
                </button>
                <form action="{{ route('videos.destroy', $video->id) }}" method="post" id="form-delete-video-{{ $video->id }}">
                  @csrf
                  @method('delete')
                </form>
              </td>
            </tr>
          @endforeach
        </tbody>
      </table>
      <div class="card-footer">
        {{ $videos->links() }}
      </div>
    </div>
  </div>
@endsection

resources/views/videos/minitutors.blade.php
@extends('layouts.app')

@section('content')
  <div class="container-fluid">
    <div class="card">
      <div class="card-header d-flex">
        <h3>Pilih MiniTutor pembuat video</h3>
        <div class="my-auto ml-auto">
          <a href="{{ route('videos.index') }}" class="btn btn-sm btn-primary">Batal</a>
        </div>
      </div>
      <div class="card-body">
        <div class="form-group">
          <form method="get" class="input-group">
            <input type="text" class="form-control" name="search" placeholder="Search..." value="{{ request()->input('search') }}">
            <span class="input-group-append">
              <button type="submit" class="btn btn-primary"><i class="fas fa-search"></i></button>
            </span>
          </form>
        </div>
      </div>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Avatar</th>
            <th>Nama</th>
            <th>Username</th>
            <th>Email</th>
            <th class="text-center" style="width: 120px;">Aksi</th>
          </tr>
        </thead>
        <tbody>
          @foreach ($minitutors as $minitutor)
            <tr>
              <td class="align-middle">
                <span class="avatar">
                  <img width="30px" src="{{ $minitutor->user->avatar_url }}" />
                </span>
              </td>
              <td class="align-middle"><a href="{{ route('videos.create', ['id' => $minitutor->id]) }}">{{ $minitutor->user->name }}</a></td>
              <td class="align-middle">{{ $minitutor->user->username }}</td>
              <td class="align-middle">{{ $minitutor->user->email }}</td>
              <td class="text-center p-0 align-middle">
                <a href="{{ route('videos.create', ['id' => $minitutor->id]) }}" class="btn btn-primary btn-sm">Pilih</a>
              </td>
            </tr>
          @endforeach
        </tbody>
      </table>
      <div class="card-footer">
        {{ $minitutors->links() }}
      </div>
    </div>
  </div>
@endsection