routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

// admin access
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

// Profile
Route::get('profile', 'ProfileController@index')->name('profile.index');
Route::get('profile/logout', 'ProfileController@logout')->name('profile.logout');


// manage permission
Route::resource('permissions', 'PermissionsController')->except(['show']);


// manage role
Route::get('roles/toggle-sync-permission/{role_id}/{permission_id}', 'RolesController@toggleSyncPermission')->name('roles.toggle.sync.permission');
Route::resource('roles', 'RolesController')->except(['show']);


// manage user
Route::prefix('users/{id}/minitutor')->as('users.minitutor.')->group(function(){
    Route::get('/create', 'UsersController@createMinitutor')->name('create');
    Route::post('/', 'UsersController@storeMinitutor')->name('store');
});
Route::get('users/{id}/followings', 'UsersController@showFollowings')->name('users.show.followings');
Route::get('users/{id}/favorites', 'UsersController@showFavorites')->name('users.show.favorites');
Route::resource('users', 'UsersController');


// manage minitutor
Route::prefix('minitutors')->as('minitutors.')->group(function(){
    Route::get('{id}/active-toggle', 'MinitutorsController@activeToggle')->name('active.toggle');
    Route::get('requests', 'MinitutorsController@requests')->name('requests');
    Route::get('request/{id}', 'MinitutorsController@showRequest')->name('request.show');
    Route::put('request/{id}/accept', 'MinitutorsController@acceptRequest')->name('request.accept');
    Route::put('request/{id}/reject', 'MinitutorsController@rejectRequest')->name('request.reject');

    Route::get('{id}/videos', 'MinitutorsController@showVideos')->name('show.videos');
    Route::get('{id}/articles', 'MinitutorsController@showArticles')->name('show.articles');
    Route::get('{id}/followers', 'MinitutorsController@showFollowers')->name('show.followers');
    Route::get('{id}/comments', 'MinitutorsController@showComments')->name('show.comments');
    Route::get('{id}/feedback', 'MinitutorsController@showFeedback')->name('show.feedback');
});
Route::resource('minitutors', 'MinitutorsController')->except(['create', 'store']);



// manage requested article
Route::get('request-articles/{id}/accept', 'RequestArticlesController@accept')->name('request-articles.accept');
Route::resource('request-articles', 'RequestArticlesController')->only(['index', 'show', 'destroy']);


// manage article
Route::get('articles/minitutors', 'ArticlesController@minitutors')->name('articles.minitutors');
Route::post('articles/{id}/image', 'ArticlesController@uploadImage')->name('articles.upload.image');
Route::resource('articles', 'ArticlesController')->except('show');


// manage requested video
Route::get('request-videos/{id}/accept', 'RequestVideosController@accept')->name('request-videos.accept');
Route::resource('request-videos', 'RequestVideosController')->only(['index', 'show', 'destroy']);


// manage video
Route::get('videos/minitutors', 'VideosController@minitutors')->name('videos.minitutors');
Route::post('videos/{id}/upload-video', 'VideosController@uploadVideo')->name('videos.upload.video');
Route::resource('videos', 'VideosController')->except('show');


// manage comments
Route::get('comments/{id}/make-public', 'CommentsController@makePublic')->name('comments.make-public');
Route::resource('comments', 'CommentsController')->only(['index', 'destroy']);


// Handele Froala fileManager
Route::get('froala/image', 'FroalaController@getImage')->name('froala.image');
Route::post('froala/image', 'FroalaController@uploadImage');
Route::delete('froala/image', 'FroalaController@destroyImage');


// manage email
Route::get('emails', 'EmailsController@index')->name('emails.index');
Route::get('emails/broadcast', 'EmailsController@broadcast')->name('emails.broadcast');
Route::post('emails/broadcast', 'EmailsController@sendBroadcastEmails');
Route::get('emails/private', 'EmailsController@private')->name('emails.private');
Route::post('emails/private', 'EmailsController@sendPrivateEmail');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('guest')->group(function(){
    Route::get('/login', 'AuthController@showLoginForm')->name('login');
    Route::post('/login', 'AuthController@login');
});

Route::middleware('auth')->post('/logout', 'AuthController@logout')->name('logout');

Route::get('/', 'RootController@index')->name('root');

app/Models/User.php
<?php

namespace App\Models;

use App\Helpers\AvatarHelper;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;
use Tymon\JWTAuth\Contracts\JWTSubject;

class User extends Authenticatable implements JWTSubject
{
    use HasFactory, Notifiable, HasRoles;

    protected $fillable = [
        'name',
        'avatar',
        'points',
        'about',
        'website',
        'username',
        'email',
        'password',
        'email_notification',
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    public function getJWTCustomClaims()
    {
        return [];
    }

    public function minitutor()
    {
        return $this->hasOne(Minitutor::class);
    }

    public function joinMinitutor()
    {
        return $this->hasOne(JoinMinitutor::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function feedback()
    {
        return $this->hasMany(Feedback::class);
    }

    public function activities()
    {
        return $this->hasMany(Activity::class);
    }

    public function favorites()
    {
        return $this->hasMany(Favorite::class);
    }

    public function followings()
    {
        return $this->hasMany(Follow::class);
    }

    public function incrementPoint($point) {
        $this->points = $this->points + $point;
        return $this->save();
    }

    public function receivesBroadcastNotificationsOn(): String
    {
        return 'App.User.'.$this->id;
    }

    /**
     * Atributes
     */
    public function getAvatarUrlAttribute()
    {
        if(!$this->avatar) {
            return 'https://ui-avatars.com/api/?bold=true&background=f0f2fc&color=677ae4&size=120&name=' . $this->name;
        }
        return AvatarHelper::getUrl($this->avatar);
    }

    public function getFollowingIdsAttribute()
    {
        return $this->followings()->select('minitutor_id')->whereHas('minitutor', function ($q) {
            $q->where('active', true);
        })->get()->map(function ($item){
            return $item->minitutor_id;
        });
    }

    public function getFavoriteIdsAttribute()
    {
        return $this->favorites()->select('post_id')->whereHas('post', function ($q) {
            $q->whereNotNull('posted_at');
        })->get()->map(function ($item){
            return $item->post_id;
        });
    }
}

app/Http/Controllers/Admin/MinitutorsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helpers\MinitutorcvHelper;
use App\Http\Controllers\Controller;
use App\Models\Minitutor;
use App\Models\JoinMinitutor;
use App\Models\Post;
use App\Models\User;
use App\Notifications\RequestMinitutorAcceptedNotification;
use App\Notifications\RequestMinitutorRejectedNotification;
use Illuminate\Http\Request;

class MinitutorsController extends Controller
{
    public function __construct()
    {
        $this->middleware(['can:manage minitutor']);
    }

    public function index(Request $request)
    {
        if (!empty($request->input('search'))) {
            $search = '%' . $request->input('search') . '%';
            $minitutors = Minitutor::whereHas('user', function ($q) use ($search) {
                return $q->where('name', 'like', $search)
                    ->orWhere('username', 'like', $search)
                    ->orWhere('email', 'like', $search);
            })->orderBy('id', 'desc');
        } else {
            $minitutors = Minitutor::orderBy('id', 'desc');
        }
        $minitutors = $minitutors->paginate(20)->appends(['search' => $request->input('search')]);
        return view('minitutors.index', ['minitutors' => $minitutors]);
    }

    public function activeToggle($id)
    {
        $minitutor = Minitutor::findOrfail($id);
        if ($minitutor->active) {
            $minitutor->active = false;
            $message = "Berhasil menonaktivkan Minitutor";
        } else {
            $minitutor->active = true;
            $message = "Berhasil mengaktivkan Minitutor";
        }
        $minitutor->save();
        return redirect()->back()->withSuccess($message);
    }

    public function requests(Request $request)
    {
        $joinMinitutors = JoinMinitutor::with('user');
        $data = $joinMinitutors->paginate(20)->appends(['search' => $request->input('search')]);
        return view('minitutors.requests', [ 'requests' => $data ]);
    }

    public function showRequest($id)
    {
        $joinMinitutor = JoinMinitutor::findOrFail($id);
        return view('minitutors.show_request', ["user" => $joinMinitutor->user, 'data' => $joinMinitutor]);
    }

    public function rejectRequest($id)
    {
        $data = JoinMinitutor::findOrFail($id);
        $user = $data->user;
        MinitutorcvHelper::destroy($data['cv']);
        $data->delete();
        $user->notify(new RequestMinitutorRejectedNotification);
        return redirect()->route('minitutors.requests')->withSuccess('Permintaan telah di ditolak.');
    }

    public function acceptRequest($id)
    {
        $data = JoinMinitutor::findOrFail($id);
        $user = $data->user;
        $arr = $data->toArray();
        MinitutorcvHelper::destroy($arr['cv']);
        unset($arr['created_at']);
        unset($arr['cv']);
        unset($arr['id']);
        unset($arr['user']);
        unset($arr['user_id']);
        unset($arr['updated_at']);
        $arr['active'] = true;
        $minitutor = new Minitutor($arr);
        $user->minitutor()->save($minitutor);
        $data->delete();
        $user->notify(new RequestMinitutorAcceptedNotification);
        return redirect()->route('minitutors.requests')->withSuccess('Permintaan telah di terima.');
    }

    public function edit($id)
    {
        $minitutor = Minitutor::findOrFail($id);
        $user = $minitutor->user;
        $last_educations = ['D1', 'D2', 'D3', 'S1', 'S2', 'S3'];
        return view('minitutors.edit', ['minitutor' => $minitutor, 'user' => $user, 'last_educations' => $last_educations]);
    }

    public function update(Request $request, $id)
    {
        $minitutor = Minitutor::findOrFail($id);
        $data = $request->validate([
            'last_education' => 'required|string|max:50',
            'university' => 'required|string|max:250',
            'city_and_country_of_study' => 'required|string|max:250',
            'majors' => 'required|string|max:250',
            'contact' => 'required|string|max:250',
        ]);
        $minitutor->update($data);
        return redirect()->back()->withSuccess('MiniTutor telah diperbarui.');
    }

    public function show($id)
    {
        $minitutor = Minitutor::findOrFail($id);
        $user = $minitutor->user;
        return view('minitutors.info', ['minitutor' => $minitutor, 'user' => $user]);
    }

    public function showArticles($id)
    {
        $minitutor = Minitutor::findOrFail($id);
        $user = $minitutor->user;
        $articles = $minitutor->articles()->get();
        return view('minitutors.articles', ['minitutor' => $minitutor, 'user' => $user, 'articles' => $articles]);
    }

    public function showVideos($id)
    {
        $minitutor = Minitutor::findOrFail($id);
        $user = $minitutor->user;
        $videos = $minitutor->videos()->get();
        return view('minitutors.videos', ['minitutor' => $minitutor, 'user' => $user, 'videos' => $videos]);
    }

    public function showFollowers($id)
    {
        $minitutor = Minitutor::findOrFail($id);
        $user = $minitutor->user;
        $followers = $minitutor->followers()->with('user')->get();
        return view('minitutors.followers', ['minitutor' => $minitutor, 'user' => $user, 'followers' => $followers]);
    }

    public function showFeedback($id)
    {
        $minitutor = Minitutor::findOrFail($id);
        $user = $minitutor->user;
        $feedback = $minitutor->feedback;
        return view('minitutors.feedback', ['minitutor' => $minitutor, 'user' => $user, 'data' => $feedback]);
    }

    public function showComments($id)
    {
        $minitutor = Minitutor::findOrFail($id);
        $user = $minitutor->user;
        $comments = $minitutor->comments;
        return view('minitutors.comments', ['minitutor' => $minitutor, 'user' => $user, 'comments' => $comments]);
    }
}

app/Http/Controllers/Api/App/MinitutorsController.php
<?php

namespace App\Http\Controllers\Api\App;

use App\Http\Controllers\Controller;
use App\Http\Resources\MinitutorResource;
use App\Http\Resources\UserResource;
use App\Http\Resources\PostResource;
use App\Models\Minitutor;
use App\Models\User;
use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;

class MinitutorsController extends Controller
{
    public function index(Request $request)
    {
        $data = Cache::remember('minitutors.page.' . $request->input('page') ?? 1, config('cache.age'), function () {
            return Minitutor::with('user')
            ->withCount([
                'posts as video_count' => function($q){
                    $q->whereNotNull('posted_at')->where('type', 'video');
                },
                'posts as article_count' => function($q){
                    $q->whereNotNull('posted_at')->where('type', 'article');
                },
                'followers'
            ])
            ->where('active', true)
            ->orderByRaw('video_count + article_count  DESC')
            ->orderBy('id')
            ->paginate(12);
        });
        $data->getCollection()->transform(function($item){
            $user = $item->user;
            unset($item->user);
            unset($item->active);
            unset($item->reason);
            unset($item->expectation);
            return [
                'user' => UserResource::make($user),
                'minitutor' => $item,
            ];
        });
        return response()->json($data, 200);
    }

    public function show($username)
    {
        $user = User::whereHas('minitutor' , function($q){
            $q->where('active', true);
        })
        ->where('username', $username)
        ->firstOrFail();
        return [
            'user' => UserResource::make($user),
            'minitutor' => MinitutorResource::make($user->minitutor),
            'followers' => $user->minitutor->followers()->get()->map(function($item){
                return UserResource::make($item->user);
            }),
            'videos' => PostResource::collection(Post::postListQuery($user->minitutor->videos())->get()),
            'articles' => PostResource::collection(Post::postListQuery($user->minitutor->articles())->get()),
        ];
    }
}

app/Http/Controllers/Api/Minitutor/CommentsController.php
<?php

namespace App\Http\Controllers\Api\Minitutor;

use App\Http\Controllers\Controller;
use App\Http\Resources\CommentResource;
use Illuminate\Http\Request;

class CommentsController extends Controller
{
    public function index(Request $request)
    {
        $user = $request->user();
        $minitutor = $user->minitutor;
        $comments = $minitutor->comments()->with(['user', 'post' => function($q){
            $q->select('id', 'slug', 'title', 'type');
        }])->whereHas('post', function($q){
            $q->whereNotNull('posted_at');
        })->where('public', true)->orderBy('id', 'desc')->get();
        return response()->json(CommentResource::collection($comments), 200);
    }
}

app/Http/Controllers/Api/Minitutor/FeedbackController.php
<?php

namespace App\Http\Controllers\Api\Minitutor;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Resources\UserResource;
use DB;
class FeedbackController extends Controller
{
    public function index(Request $request)
    {
        $user = $request->user();
        $minitutor = $user->minitutor;
        $feedback = $minitutor->feedback()
        ->with(['user', 'post' => function($q){
            $q->select('id', 'slug', 'title', 'type');
        }])
        ->whereHas('post', function($q){
            $q->whereNotNull('posted_at');
        })
        ->get()->map(function($item){
            $temp = $item->toArray();
            $temp['rating'] = $item->rating;
            $temp['user'] = UserResource::make($item->user);
            return $temp;
        });
        return response()->json($feedback, 200);
    }
}

resources/views/minitutors/articles.blade.php
@extends('layouts.app')

@section('content')
  <x-minitutor-wrapper :minitutor="$minitutor">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Judul</th>
          <th>Kategori</th>
          <th>Status</th>
          <th>Dibuat pada</th>
          <th class="text-center" style="width: 120px;">Aksi</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($articles as $article)
          <tr>
            <td class="font-weight-bold align-middle">{{ $article->title }}</td>
            <td class="font-weight-bold align-middle">{{ $article->category ? $article->category->name : '-' }}</td>
            <td class="font-weight-bold align-middle">{{ $article->posted_at }}</td>
            <td class="font-weight-bold align-middle">{{ $article->created_at }}</td>
            <td class="text-center py-0 align-middle">
              <a href="{{ route('articles.edit', $article->id) }}" class="btn btn-default btn-sm" title="Edit">
                <i class="fas fa-edit"></i>
              </a>
              <button class="btn btn-danger btn-sm btn-icon" title="Delete" delete-confirm="#form-delete-article-{{ $article->id }}">
                <i class="fas fa-trash"></i>
              </button>
              <form action="{{ route('articles.destroy', $article->id) }}" method="post" id="form-delete-article-{{ $article->id }}">
                @csrf
                @method('delete')
              </form>
            </td>
          </tr>
        @endforeach
      </tbody>
    </table>
  </x-minitutor-wrapper>
@endsection

resources/views/minitutors/followers.blade.php
@extends('layouts.app')

@section('content')
  <x-minitutor-wrapper :minitutor="$minitutor">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Avatar</th>
          <th>Nama</th>
          <th>Username</th>
          <th>Email</th>
          <th class="text-center" style="width: 140px;">Aksi</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($followers as $follower)
          <tr>
            <td class="align-middle">
              <span class="avatar">
                <img src="{{ $follower->user->avatar_url }}" />
              </span>
            </td>
            <td class="align-middle"><a href="{{ route('users.show', $follower->user->id) }}">{{ $follower->user->name }}</a></td>
            <td class="align-middle">{{ $follower->user->username }}</td>
            <td class="align-middle">{{ $follower->user->email }}</td>
            <td class="text-center py-0 align-middle">
              <a href="{{ route('users.show', $follower->user->id) }}" class="btn btn-default btn-sm"><i class="fas fa-eye"></i></a>
              <a href="{{ route('users.edit', $follower->user->id) }}" class="btn btn-default btn-sm"><i class="fas fa-edit"></i></a>
            </td>
          </tr>
        @endforeach
      </tbody>
    </table>
  </x-minitutor-wrapper>
@endsection

resources/views/minitutors/index.blade.php
@extends('layouts.app')

@section('content')
  <div class="container-fluid">
    <div class="card">
      <div class="card-header d-flex">
        <h3>MiniTutor</h3>
        <div class="my-auto ml-auto">
          <a href="{{ route('minitutors.requests') }}" class="btn btn-sm btn-danger">Permintaan Jadi MiniTutor</a>
        </div>
      </div>
      <div class="card-body">
        <div class="form-group">
          <form method="get" class="input-group">
            <input type="text" class="form-control" name="search" placeholder="Search..." value="{{ request()->input('search') }}">
            <span class="input-group-append">
              <button type="submit" class="btn btn-primary"><i class="fas fa-search"></i></button>
            </span>
          </form>
        </div>
      </div>
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Avatar</th>
            <th>Nama</th>
            <th>Poin</th>
            <th>Username</th>
            <th>Email</th>
            <th>Status</th>
            <th>Dibuat pada</th>
            <th class="text-center" style="width: 120px;">Aksi</th>
          </tr>
        </thead>
        <tbody>
          @foreach ($minitutors as $minitutor)
            <tr>
              <td class="align-middle">
                <img width="33px" src="{{ $minitutor->user->avatar_url }}" />
              </td>
              <td class="align-middle"><a href="{{ route('minitutors.show', $minitutor->id) }}">{{ $minitutor->user->name }}</a></td>
              <td class="align-middle">{{ $minitutor->user->points }}</td>
              <td class="align-middle">{{ $minitutor->user->username }}</td>
              <td class="align-middle">{{ $minitutor->user->email }}</td>
              <td class="align-middle">{{ $minitutor->active ? 'Aktif' : 'Tidak Aktif' }}</td>
              <td class="align-middle">{{ $minitutor->created_at->format('d-M-Y') }}</td>
              <td class="text-center p-0 align-middle">
                <a href="{{ route('minitutors.show', $minitutor->id) }}" class="btn btn-default btn-sm"><i class="fas fa-eye"></i></a>
              </td>
            </tr>
          @endforeach
        </tbody>
      </table>
      <div class="card-footer">
        {{ $minitutors->links() }}
      </div>
    </div>
  </div>
@endsection

resources/views/minitutors/requests.blade.php
@extends('layouts.app')

@section('content')
  <div class="container-fluid">
    <div class="card">
      <div class="card-header d-flex">
        <h3>Permintaan jadi MiniTutor</h3>
        <div class="my-auto ml-auto">
          <a href="{{ route('minitutors.index') }}" class="btn btn-sm btn-primary">Kembali</a>
        </div>
      </div>
      <table class="table table-hover m-0">
        <thead>
          <tr>
            <th>Avatar</th>
            <th>Nama</th>
            <th>Username</th>
            <th>Email</th>
            <th class="text-center" style="width: 120px;">Aksi</th>
          </tr>
        </thead>
        <tbody>
          @foreach ($requests as $data)
            <tr>
              <td class="align-middle">
                <span class="avatar">
                  <img width="30px" src="{{ $data->user->avatar_url }}" />
                </span>
              </td>
              <td class="align-middle"><a href="{{ route('users.show', $data->user->id) }}">{{ $data->user->name }}</a></td>
              <td class="align-middle">{{ $data->user->username }}</td>
              <td class="align-middle">{{ $data->user->email }}</td>
              <td class="text-center p-0 align-middle">
                <a href="{{ route('minitutors.request.show', $data->id) }}" class="btn btn-default btn-sm"><i class="fas fa-eye"></i></a>
              </td>
            </tr>
          @endforeach
        </tbody>
      </table>
      <div class="card-footer">
        {{ $requests->links() }}
      </div>
    </div>
  </div>
@endsection

resources/views/minitutors/show_request.blade.php
@extends('layouts.app')

@section('content')
  <div class="container-fluid">
    <div class="card">
      <div class="card-header d-flex">
        <h3>Data permintaan jadi MiniTutor</h3>
        <div class="my-auto ml-auto">
          <a class="btn btn-sm btn-primary" href="{{ route('minitutors.requests') }}">Batal</a>
          <button class="btn btn-sm btn-success" onclick="$('#form-accept-request').submit()">Terima</button>
          <button class="btn btn-sm btn-danger" onclick="$('#form-reject-request').submit()">Tolak</button>

          <form action="{{ route('minitutors.request.reject', $data->id) }}" id="form-reject-request" method="post" class="d-none">
            @csrf
            @method('put')
          </form>
          <form action="{{ route('minitutors.request.accept', $data->id) }}" id="form-accept-request" method="post" class="d-none">
            @csrf
            @method('put')
          </form>
        </div>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-lg-2 col-md-4 mb-30 text-center">
            <a href="#show-activity" class="avatar avatar-100">
              <img alt="photo" src="{{ $user->avatar_url }}">
            </a>
            <a download href="{{ $data->cvUrl }}" target="_blank" class="btn btn-block btn-primary btn-sm mt-15">DOWNLOAD CV</a>
          </div>
          <div class="col-lg-10 col-md-6 mb-3">
            <h5 class="mb-0 mt-0">Nama</h5>
            <p class="mb-30"><a href="{{ route('users.show', $user->id) }}">{{ $user->name }}</a></p>
            <h5 class="mb-0 mt-30">Username</h5>
            <p class="mb-30">{{ $user->username }}</p>
            <h5 class="mb-0 mt-30">Email</h5>
            <p class="mb-30">{{ $user->email }}</p>
            <h5 class="mb-0 mt-30">Email di verifikasi</h5>
            <p class="mb-30">{{ $user->email_verified_at ?? 'Tidak' }}</p>

            <h5 class="mb-0 mt-30">Pedidikan terakhir</h5>
            <p class="mb-30"><strong>{{ $data->last_education }}</strong></p>
            <h5 class="mb-0 mt-30">Universitas</h5>
            <p class="mb-30"><strong>{{ $data->university }}</strong></p>
            <h5 class="mb-0 mt-30">Kota dan negara tempat study</h5>
            <p class="mb-30"><strong>{{ $data->city_and_country_of_study }}</strong></p>
            <h5 class="mb-0 mt-30">Jurusan</h5>
            <p class="mb-30"><strong>{{ $data->majors }}</strong></p>

            <h5 class="mb-0 mt-30">Spesialisasi/Minat bakat</h5>
            <p class="mb-30">{{ $data->interest_talent }}</p>
            <h5 class="mb-0 mt-30">Kontak (Whatsapp)</h5>
            <p class="mb-30">{{ $data->contact }}</p>
            <h5 class="mb-0 mt-30">Motivasi</h5>
            <p class="mb-30">{{ $data->reason }}</p>
            <h4 class="mt-30">Ekspektasi</h4>
            <p class="mb-30">{{ $data->expectation }}</p>

          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/minitutors/videos.blade.php
@extends('layouts.app')

@section('content')
  <x-minitutor-wrapper :minitutor="$minitutor">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Judul</th>
          <th>Kategori</th>
          <th>Status</th>
          <th>Dibuat pada</th>
          <th class="text-center" style="width: 120px;">Aksi</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($videos as $video)
          <tr>
            <td class="font-weight-bold align-middle">{{ $video->title }}</td>
            <td class="font-weight-bold align-middle">{{ $video->category ? $video->category->name : '-' }}</td>
            <td class="font-weight-bold align-middle">{{ $video->posted_at }}</td>
            <td class="font-weight-bold align-middle">{{ $video->created_at }}</td>
            <td class="text-center py-0 align-middle">
              <a href="{{ route('videos.edit', $video->id) }}" class="btn btn-default btn-sm" title="Edit">
                <i class="fas fa-edit"></i>
              </a>
              <button class="btn btn-danger btn-sm btn-icon" title="Delete" delete-confirm="#form-delete-video-{{ $video->id }}">
                <i class="fas fa-trash"></i>
              </button>
              <form action="{{ route('videos.destroy', $video->id) }}" method="post" id="form-delete-video-{{ $video->id }}">
                @csrf
                @method('delete')
              </form>
            </td>
          </tr>
        @endforeach
      </tbody>
    </table>
  </x-minitutor-wrapper>
@endsection